import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { Link, useNavigate, useParams } from "@tanstack/react-router";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  Calendar,
  CheckCircle2,
  Clock,
  ExternalLink,
  MapPin,
  Navigation,
  Phone,
  Printer,
  Share2,
  Star,
  User,
} from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useGetAnalyses } from "../hooks/use-backend";
import { useDoctors } from "../hooks/use-doctors";
import type { DoctorInfo } from "../types";

function DoctorCard({ doctor }: { doctor: DoctorInfo }) {
  const mapsUrl = `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(
    `${doctor.address}, ${doctor.city}`,
  )}`;

  return (
    <div className="card-medical p-4" data-ocid="doctor-card">
      <div className="flex items-start gap-3 mb-3">
        <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
          <Activity size={18} className="text-primary" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="font-semibold text-foreground text-sm truncate">
            {doctor.name}
          </p>
          <p className="text-xs text-muted-foreground mt-0.5">
            {doctor.specialty}
          </p>
        </div>
        <div className="flex items-center gap-0.5 shrink-0">
          <Star
            size={12}
            className="text-warning-foreground fill-warning-foreground"
          />
          <span className="text-xs font-semibold text-foreground">
            {doctor.rating}
          </span>
        </div>
      </div>

      <div className="flex flex-col gap-1.5 mb-3">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <MapPin size={12} className="shrink-0" />
          <span className="truncate">
            {doctor.address}, {doctor.city}
          </span>
        </div>
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Phone size={12} className="shrink-0" />
          <span>{doctor.phone}</span>
        </div>
        {doctor.distanceKm !== undefined && (
          <div className="flex items-center gap-2 text-xs text-accent">
            <Navigation size={12} className="shrink-0" />
            <span>{doctor.distanceKm} km away</span>
          </div>
        )}
      </div>

      <a
        href={mapsUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex"
        data-ocid="get-directions-btn"
      >
        <Button size="sm" variant="outline" className="gap-1.5 text-xs">
          <ExternalLink size={12} />
          Get Directions
        </Button>
      </a>
    </div>
  );
}

function SectionHeading({
  icon: Icon,
  title,
}: {
  icon: React.FC<{ size?: number; className?: string }>;
  title: string;
}) {
  return (
    <h2 className="font-semibold text-foreground text-sm mb-3 flex items-center gap-2">
      <Icon size={14} className="text-primary shrink-0" />
      {title}
    </h2>
  );
}

export default function AnalysisDetailPage() {
  const { id } = useParams({ from: "/analysis/$id" });
  const navigate = useNavigate();
  const { data: analyses, isLoading } = useGetAnalyses();
  const { getNearbyDoctors } = useDoctors();
  const [userCoords, setUserCoords] = useState<{
    lat: number;
    lon: number;
  } | null>(null);

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (pos) =>
          setUserCoords({
            lat: pos.coords.latitude,
            lon: pos.coords.longitude,
          }),
        () => setUserCoords(null),
      );
    }
  }, []);

  const analysis = analyses?.find((a) => a.analysisId === id);
  const nearbyDoctors = getNearbyDoctors(userCoords?.lat, userCoords?.lon, 5);

  const handleShare = async () => {
    const shareData = {
      title: `DermaAI Analysis – ${analysis?.predictedDisease ?? ""}`,
      text: `AI skin analysis result: ${analysis?.predictedDisease} (${analysis?.confidence}% confidence). Generated by DermaAI.`,
      url: window.location.href,
    };
    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        await navigator.clipboard.writeText(window.location.href);
        toast.success("Report link copied to clipboard!");
      }
    } catch {
      // user cancelled or error — silently ignore
    }
  };

  if (isLoading) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-8 flex flex-col gap-4">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-48 w-full rounded-2xl" />
        <Skeleton className="h-32 w-full rounded-xl" />
        <Skeleton className="h-32 w-full rounded-xl" />
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-16 flex flex-col items-center gap-4 text-center">
        <div className="w-16 h-16 rounded-2xl bg-muted flex items-center justify-center">
          <Activity size={28} className="text-muted-foreground" />
        </div>
        <p className="font-semibold text-foreground">Analysis not found</p>
        <p className="text-sm text-muted-foreground">
          This report may have been deleted or the link is incorrect.
        </p>
        <Link to="/dashboard">
          <Button variant="outline" className="gap-2">
            <ArrowLeft size={16} />
            Back to Dashboard
          </Button>
        </Link>
      </div>
    );
  }

  const dateObj = new Date(analysis.timestamp);
  const dateFormatted = dateObj.toLocaleDateString("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const timeFormatted = dateObj.toLocaleTimeString("en-GB", {
    hour: "2-digit",
    minute: "2-digit",
  });

  return (
    <div className="max-w-2xl mx-auto px-4 py-6 print:max-w-none print:px-6">
      {/* Back nav — hidden on print */}
      <div className="flex items-center justify-between mb-6 print:hidden">
        <button
          type="button"
          onClick={() => navigate({ to: "/dashboard" })}
          className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-smooth"
          data-ocid="back-to-dashboard"
        >
          <ArrowLeft size={16} />
          Dashboard
        </button>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5"
            onClick={handleShare}
            data-ocid="share-report-btn"
          >
            <Share2 size={14} />
            Share
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5"
            onClick={() => window.print()}
            data-ocid="print-report-btn"
          >
            <Printer size={14} />
            Print
          </Button>
        </div>
      </div>

      {/* Print-only header */}
      <div className="hidden print:block mb-6">
        <h1 className="text-2xl font-bold">DermaAI — Skin Analysis Report</h1>
        <p className="text-sm text-muted-foreground">Generated by DermaAI</p>
      </div>

      {/* AI Disclaimer — prominent, top of report */}
      <div
        className="flex gap-3 p-4 rounded-xl border-2 border-warning/40 bg-warning/8 mb-5"
        role="alert"
        data-ocid="ai-disclaimer"
      >
        <AlertTriangle
          size={20}
          className="text-warning-foreground shrink-0 mt-0.5"
        />
        <div>
          <p className="text-sm font-semibold text-foreground mb-0.5">
            AI Disclaimer
          </p>
          <p className="text-xs text-foreground/80 leading-relaxed">
            This result is generated by an AI system and may not always be
            accurate. It should not replace professional medical diagnosis.
            Please consult a certified dermatologist for confirmation.
          </p>
        </div>
      </div>

      {/* Analysis header card */}
      <div className="card-medical p-5 mb-5">
        <div className="flex gap-4 items-start mb-4">
          {analysis.imageUrl ? (
            <img
              src={analysis.imageUrl}
              alt="Skin analysis"
              className="w-24 h-24 rounded-xl object-cover bg-muted shrink-0 border border-border"
            />
          ) : (
            <div className="w-24 h-24 rounded-xl bg-muted flex items-center justify-center shrink-0">
              <Activity size={28} className="text-muted-foreground" />
            </div>
          )}
          <div className="flex-1 min-w-0">
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">
              Possible Condition
            </p>
            <h1 className="font-display text-xl font-bold text-foreground leading-tight mb-2">
              {analysis.predictedDisease}
            </h1>
            <div className="bg-accent/15 border border-accent/20 rounded-lg px-3 py-1.5 inline-flex items-center gap-2">
              <span className="text-accent font-bold text-lg font-display">
                {analysis.confidence}%
              </span>
              <span className="text-accent/80 text-xs uppercase tracking-wide">
                AI Confidence
              </span>
            </div>
          </div>
        </div>

        <Separator className="my-3" />

        {/* Meta info */}
        <div className="grid grid-cols-2 gap-3 text-xs">
          <div className="flex items-center gap-2 text-muted-foreground">
            <Calendar size={12} className="shrink-0" />
            <span>{dateFormatted}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground">
            <Clock size={12} className="shrink-0" />
            <span>{timeFormatted}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground">
            <User size={12} className="shrink-0" />
            <span>Age: {analysis.ageGroup}</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground">
            <Clock size={12} className="shrink-0" />
            <span>Duration: {analysis.duration}</span>
          </div>
        </div>

        {analysis.symptoms.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mt-3">
            {analysis.symptoms.map((s) => (
              <Badge key={s} variant="secondary" className="text-xs">
                {s}
              </Badge>
            ))}
          </div>
        )}

        {analysis.explanation && (
          <p className="text-sm text-foreground/80 leading-relaxed mt-3">
            {analysis.explanation}
          </p>
        )}
      </div>

      {/* Causes */}
      <div className="card-medical p-4 mb-4">
        <SectionHeading icon={AlertCircle} title="Possible Causes" />
        <ul className="flex flex-col gap-2">
          {analysis.causes.map((c) => (
            <li
              key={c}
              className="text-sm text-foreground/80 flex items-start gap-2"
            >
              <span className="text-primary mt-1 shrink-0 text-xs">●</span>
              {c}
            </li>
          ))}
        </ul>
      </div>

      {/* Treatments */}
      <div className="card-medical p-4 mb-4">
        <SectionHeading icon={CheckCircle2} title="Treatment &amp; Care" />
        <ul className="flex flex-col gap-2">
          {analysis.treatments.map((t) => (
            <li
              key={t}
              className="text-sm text-foreground/80 flex items-start gap-2"
            >
              <span className="text-accent mt-0.5 shrink-0 font-bold">✓</span>
              {t}
            </li>
          ))}
        </ul>
      </div>

      {/* Lifestyle tips */}
      <div className="card-medical p-4 mb-4">
        <SectionHeading icon={Activity} title="Lifestyle Tips" />
        <ul className="flex flex-col gap-2">
          {analysis.lifestyleTips.map((tip) => (
            <li
              key={tip}
              className="text-sm text-foreground/80 flex items-start gap-2"
            >
              <span className="text-primary/70 mt-0.5 shrink-0">→</span>
              {tip}
            </li>
          ))}
        </ul>
      </div>

      {/* Doctor advice */}
      <div className="p-4 rounded-xl bg-warning/8 border border-warning/30 mb-6">
        <h2 className="font-semibold text-foreground text-sm mb-2 flex items-center gap-2">
          <AlertTriangle
            size={14}
            className="text-warning-foreground shrink-0"
          />
          When to See a Doctor
        </h2>
        <p className="text-sm text-foreground/80 leading-relaxed">
          {analysis.doctorAdvice}
        </p>
      </div>

      {/* Nearby doctors — hidden on print */}
      <div className="mb-6 print:hidden">
        <h2 className="font-display font-semibold text-base text-foreground mb-1 flex items-center gap-2">
          <MapPin size={16} className="text-primary" />
          Nearby Dermatologists
        </h2>
        <p className="text-xs text-muted-foreground mb-4">
          {userCoords
            ? "Sorted by distance from your current location."
            : "Enable location access for distance-sorted results."}
        </p>
        <div
          className="grid grid-cols-1 sm:grid-cols-2 gap-3"
          data-ocid="doctors-list"
        >
          {nearbyDoctors.map((doctor) => (
            <DoctorCard key={doctor.id} doctor={doctor} />
          ))}
        </div>
      </div>

      {/* Bottom actions — hidden on print */}
      <div className="flex gap-3 justify-center print:hidden">
        <Button
          variant="outline"
          onClick={() => navigate({ to: "/dashboard" })}
          className="gap-2"
          data-ocid="back-dashboard-btn"
        >
          <ArrowLeft size={16} />
          Back to Dashboard
        </Button>
        <Button
          variant="outline"
          onClick={handleShare}
          className="gap-2"
          data-ocid="share-report-bottom-btn"
        >
          <Share2 size={16} />
          Share
        </Button>
        <Button
          variant="outline"
          onClick={() => window.print()}
          className="gap-2"
          data-ocid="print-report-bottom-btn"
        >
          <Printer size={16} />
          Print
        </Button>
      </div>
    </div>
  );
}
