/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnalysisRecord = IDL.Record({
  'duration' : IDL.Text,
  'explanation' : IDL.Text,
  'lifestyleTips' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'predictedDisease' : IDL.Text,
  'analysisId' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'doctorAdvice' : IDL.Text,
  'symptoms' : IDL.Vec(IDL.Text),
  'causes' : IDL.Vec(IDL.Text),
  'treatments' : IDL.Vec(IDL.Text),
  'confidence' : IDL.Float64,
  'ageGroup' : IDL.Text,
});
export const ConsentRecord = IDL.Record({
  'timestamp' : IDL.Int,
  'camera' : IDL.Bool,
  'location' : IDL.Bool,
  'dataUsage' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getAnalysis' : IDL.Func([IDL.Text], [IDL.Opt(AnalysisRecord)], ['query']),
  'getConsent' : IDL.Func([], [IDL.Opt(ConsentRecord)], ['query']),
  'saveAnalysis' : IDL.Func([AnalysisRecord], [IDL.Text], []),
  'saveConsent' : IDL.Func([IDL.Bool, IDL.Bool, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnalysisRecord = IDL.Record({
    'duration' : IDL.Text,
    'explanation' : IDL.Text,
    'lifestyleTips' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'predictedDisease' : IDL.Text,
    'analysisId' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'doctorAdvice' : IDL.Text,
    'symptoms' : IDL.Vec(IDL.Text),
    'causes' : IDL.Vec(IDL.Text),
    'treatments' : IDL.Vec(IDL.Text),
    'confidence' : IDL.Float64,
    'ageGroup' : IDL.Text,
  });
  const ConsentRecord = IDL.Record({
    'timestamp' : IDL.Int,
    'camera' : IDL.Bool,
    'location' : IDL.Bool,
    'dataUsage' : IDL.Bool,
  });
  
  return IDL.Service({
    'getAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getAnalysis' : IDL.Func([IDL.Text], [IDL.Opt(AnalysisRecord)], ['query']),
    'getConsent' : IDL.Func([], [IDL.Opt(ConsentRecord)], ['query']),
    'saveAnalysis' : IDL.Func([AnalysisRecord], [IDL.Text], []),
    'saveConsent' : IDL.Func([IDL.Bool, IDL.Bool, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };